name: "Automated Tests"
on: [push, pull_request, workflow_dispatch]
permissions:
  id-token: write
  contents: read
  checks: write
jobs:
  bash-compat:
    name: "bash ${{ matrix.bash-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bash-version:
          - "4.2.53"
          - "4.3.30"
          - "4.4.18"
          - "5.0"
          - "5.1.16"
          - "5.2.37"
          - "5.3"
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev
      - name: "Build & test bash ${{ matrix.bash-version }}"
        run: bash test/bash-compat.sh "${{ matrix.bash-version }}"
      - name: Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: "BATS Test Report (bash ${{ matrix.bash-version }})"
          path: report.xml
          reporter: java-junit
          fail-on-error: true

  zsh-compat:
    name: "zsh tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Run zsh tests
        run: test/bats/bin/bats test/*-zsh.bats test/zsh-completion-descriptions.bats --formatter junit > report-zsh.xml
      - name: Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: "BATS Test Report (zsh)"
          path: report-zsh.xml
          reporter: java-junit
          fail-on-error: true

  macos:
    name: "macOS zsh tests"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Run zsh tests
        run: test/bats/bin/bats test/*-zsh.bats test/zsh-completion-descriptions.bats --formatter junit > report-macos-zsh.xml
      - name: Report
        uses: dorny/test-reporter@v3
        if: always()
        with:
          name: "BATS Test Report (macOS zsh)"
          path: report-macos-zsh.xml
          reporter: java-junit
          fail-on-error: true
